/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Microsoft
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnOk3 = new javax.swing.JButton();
        BtnOk4 = new javax.swing.JButton();
        BtnOk1 = new javax.swing.JButton();
        BtnOk2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 102));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Operator");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 130, 70, 19);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("Hasil");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 190, 40, 19);

        BtnOk3.setText("/");
        BtnOk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOk3ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnOk3);
        BtnOk3.setBounds(130, 160, 50, 23);

        BtnOk4.setText("+");
        BtnOk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOk4ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnOk4);
        BtnOk4.setBounds(190, 160, 50, 23);

        BtnOk1.setText("-");
        BtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOk1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnOk1);
        BtnOk1.setBounds(260, 160, 50, 23);

        BtnOk2.setText("X");
        BtnOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOk2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnOk2);
        BtnOk2.setBounds(70, 160, 50, 23);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Bilangan 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 90, 80, 19);

        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        jPanel1.add(bil1);
        bil1.setBounds(140, 50, 180, 30);
        jPanel1.add(bil3);
        bil3.setBounds(140, 90, 180, 30);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("Kalkulator Sederhana");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 20, 160, 19);

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Bilangan 1");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 50, 80, 19);

        Hasil.setEditable(false);
        jPanel1.add(Hasil);
        Hasil.setBounds(50, 220, 290, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOk3ActionPerformed
        double bilangan1 = Integer.parseInt(bil1.getText());
        double bilangan2 = Integer.parseInt(bil3.getText());
        double hasilbagi = bilangan1/bilangan2;

        Hasil.setText(String.valueOf(hasilbagi));
    }//GEN-LAST:event_BtnOk3ActionPerformed

    private void BtnOk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOk4ActionPerformed
        int bilangan1 = Integer.parseInt(bil1.getText());
        int bilangan2 = Integer.parseInt(bil3.getText());
        int hasiltambah = bilangan1+bilangan2;

        Hasil.setText(String.valueOf(hasiltambah));
    }//GEN-LAST:event_BtnOk4ActionPerformed

    private void BtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOk1ActionPerformed
        int bilangan1 = Integer.parseInt(bil1.getText());
        int bilangan2 = Integer.parseInt(bil3.getText());
        int hasilkurang = bilangan1-bilangan2;

        Hasil.setText(String.valueOf(hasilkurang));
    }//GEN-LAST:event_BtnOk1ActionPerformed

    private void BtnOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOk2ActionPerformed
        int bilangan1 = Integer.parseInt(bil1.getText());
        int bilangan2 = Integer.parseInt(bil3.getText());
        int hasilkali = bilangan1*bilangan2;

        Hasil.setText(String.valueOf(hasilkali));

    }//GEN-LAST:event_BtnOk2ActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk1;
    private javax.swing.JButton BtnOk2;
    private javax.swing.JButton BtnOk3;
    private javax.swing.JButton BtnOk4;
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
